services:
  backend:
    build: ./backend
    environment:
      - TZ=America/Chicago
    expose:
      - "8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
    environment:
      - TZ=America/Chicago
    expose:
      - "80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - backend
      - frontend
